**1)Define the following metrics and perform the following operations**

i)	Write a Python program using Python Lists

ii)	Write a Python program and NumPy

Matrix A =  [[ 3.7827  3.3454  3.2341]  , [ 2.2122  3.5678  3.9087] , 
[1.1234  2.8934,  5.9087]].

Matrix B =  [[ 3.1234  3.0987  3.1234]  , [ 2.1111  3.2222  3.3333] , 
[1.0987  1.3456,  5.1234]].

Matrix C =  [[ 3.1243  3.0989  3.1256 ]  , [ 2.6721  3.6785  3.9017] , 
[1.1254  2.8956,  5.9187]].

**i) Write a Python program using Python Lists**

In [1]:
# Define matrices
A = [[3.7827, 3.3454, 3.2341], [2.2122, 3.5678, 3.9087], [1.1234, 2.8934, 5.9087]]
B = [[3.1234, 3.0987, 3.1234], [2.1111, 3.2222, 3.3333], [1.0987, 1.3456, 5.1234]]
C = [[3.1243, 3.0989, 3.1256], [2.6721, 3.6785, 3.9017], [1.1254, 2.8956, 5.9187]]

# Matrix addition
def add_matrices(mat1, mat2):
    return [[mat1[i][j] + mat2[i][j] for j in range(len(mat1[0]))] for i in range(len(mat1))]

# Matrix subtraction
def subtract_matrices(mat1, mat2):
    return [[mat1[i][j] - mat2[i][j] for j in range(len(mat1[0]))] for i in range(len(mat1))]

# Matrix multiplication (element-wise)
def multiply_matrices(mat1, mat2):
    return [[mat1[i][j] * mat2[i][j] for j in range(len(mat1[0]))] for i in range(len(mat1))]

# Sum of each matrix
def sum_matrix(mat):
    return sum(sum(row) for row in mat)

# Perform operations
add_AB = add_matrices(A, B)
subtract_AB = subtract_matrices(A, B)
multiply_AB = multiply_matrices(A, B)

add_BC = add_matrices(B, C)
subtract_BC = subtract_matrices(B, C)
multiply_BC = multiply_matrices(B, C)

# Print results
print("Addition of A and B:", add_AB)
print("\nSubtraction of A and B:", subtract_AB)
print("\nElement-wise multiplication of A and B:", multiply_AB)
print("\nSum of Matrix A:", sum_matrix(A))
print("\nSum of Matrix B:", sum_matrix(B))
print("\nSum of Matrix C:", sum_matrix(C))


Addition of A and B: [[6.9061, 6.444100000000001, 6.3575], [4.3233, 6.79, 7.242], [2.2221, 4.239, 11.0321]]

Subtraction of A and B: [[0.6593, 0.24670000000000014, 0.11070000000000002], [0.10110000000000019, 0.34560000000000013, 0.5754000000000001], [0.024699999999999944, 1.5478000000000003, 0.7852999999999994]]

Element-wise multiplication of A and B: [[11.814885180000001, 10.36639098, 10.10138794], [4.6701754200000005, 11.49616516, 13.02886971], [1.23427958, 3.89335904, 30.27263358]]

Sum of Matrix A: 29.976399999999998

Sum of Matrix B: 25.5798

Sum of Matrix C: 29.540800000000004


**ii) Write a Python program and NumPy**

In [2]:
import numpy as np
# Define matrices
A = np.array([[3.7827, 3.3454, 3.2341], [2.2122, 3.5678, 3.9087], [1.1234, 2.8934, 5.9087]])
B = np.array([[3.1234, 3.0987, 3.1234], [2.1111, 3.2222, 3.3333], [1.0987, 1.3456, 5.1234]])
C = np.array([[3.1243, 3.0989, 3.1256], [2.6721, 3.6785, 3.9017], [1.1254, 2.8956, 5.9187]])

# Matrix addition
add_AB = A + B
add_BC = B + C

# Matrix subtraction
subtract_AB = A - B
subtract_BC = B - C

# Matrix multiplication (element-wise)
multiply_AB = A * B
multiply_BC = B * C

# Sum of each matrix
sum_A = np.sum(A)
sum_B = np.sum(B)
sum_C = np.sum(C)

# Print results
print("Addition of A and B:\n", add_AB)
print("Subtraction of A and B:\n", subtract_AB)
print("Element-wise multiplication of A and B:\n", multiply_AB)
print("Addition of B and C:\n", add_BC)
print("Subtraction of B and C:\n", subtract_BC)
print("Element-wise multiplication of B and C:\n", multiply_BC)
print("Sum of Matrix A:", sum_A)
print("Sum of Matrix B:", sum_B)
print("Sum of Matrix C:", sum_C)  

Addition of A and B:
 [[ 6.9061  6.4441  6.3575]
 [ 4.3233  6.79    7.242 ]
 [ 2.2221  4.239  11.0321]]
Subtraction of A and B:
 [[0.6593 0.2467 0.1107]
 [0.1011 0.3456 0.5754]
 [0.0247 1.5478 0.7853]]
Element-wise multiplication of A and B:
 [[11.81488518 10.36639098 10.10138794]
 [ 4.67017542 11.49616516 13.02886971]
 [ 1.23427958  3.89335904 30.27263358]]
Addition of B and C:
 [[ 6.2477  6.1976  6.249 ]
 [ 4.7832  6.9007  7.235 ]
 [ 2.2241  4.2412 11.0421]]
Subtraction of B and C:
 [[-9.000e-04 -2.000e-04 -2.200e-03]
 [-5.610e-01 -4.563e-01 -5.684e-01]
 [-2.670e-02 -1.550e+00 -7.953e-01]]
Element-wise multiplication of B and C:
 [[ 9.75843862  9.60256143  9.76249904]
 [ 5.64107031 11.8528627  13.00553661]
 [ 1.23647698  3.89631936 30.32386758]]
Sum of Matrix A: 29.9764
Sum of Matrix B: 25.579800000000002
Sum of Matrix C: 29.5408


**2)	Write a Python Program and perform the following operations ?**

I.	  Create a List {1225, 4986, 6789, 7890, 2345, 6783, 0987, 1234, 8765, 3456}

II.	  Iterate using a for loop

III.  Iterate using for loop and range

IV.	  List Comprehension

V.	  Enumerate

VI.	  Iter function and next function

VII.  Map function

VIII. Using zip

IX.   Using NumPy Module

In [3]:
# I. Create a List
numbers = [1225, 4986, 6789, 7890, 2345, 6783, 987, 1234, 8765, 3456]

# II. Iterate using a for loop
print("Iterating using a for loop:")
for num in numbers:
    print(num, end=' ')
print("\n")

# III. Iterate using a for loop and range
print("Iterating using a for loop and range:")
for i in range(len(numbers)):
    print(numbers[i], end=' ')
print("\n")

# IV. List Comprehension
squared_numbers = [num ** 2 for num in numbers]
print("Squared numbers using list comprehension:")
print(squared_numbers)
print("\n")

# V. Enumerate
print("Iterating using enumerate:")
for index, num in enumerate(numbers):
    print(f"Index {index}: {num}")
print("\n")

# VI. Iter function and next function
print("Using iter and next functions:")
numbers_iter = iter(numbers)
print(next(numbers_iter))  # prints the first element
print(next(numbers_iter))  # prints the second element
print("\n")

# VII. Map function
print("Using map function to double the numbers:")
doubled_numbers = list(map(lambda x: x * 2, numbers))
print(doubled_numbers)
print("\n")

# VIII. Using zip
print("Using zip function to pair elements with their index:")
indexed_numbers = list(zip(range(len(numbers)), numbers))
print(indexed_numbers)
print("\n")

# IX. Using NumPy Module
import numpy as np

print("Using NumPy module to perform operations on the list:")
np_numbers = np.array(numbers)

# Adding 10 to each element
np_addition = np_numbers + 10
print("Adding 10 to each element:")
print(np_addition)

# Multiplying each element by 2
np_multiplication = np_numbers * 2
print("\nMultiplying each element by 2:")
print(np_multiplication)

# Calculating the mean of the list
np_mean = np.mean(np_numbers)
print("\nMean of the list:")
print(np_mean)

Iterating using a for loop:
1225 4986 6789 7890 2345 6783 987 1234 8765 3456 

Iterating using a for loop and range:
1225 4986 6789 7890 2345 6783 987 1234 8765 3456 

Squared numbers using list comprehension:
[1500625, 24860196, 46090521, 62252100, 5499025, 46009089, 974169, 1522756, 76825225, 11943936]


Iterating using enumerate:
Index 0: 1225
Index 1: 4986
Index 2: 6789
Index 3: 7890
Index 4: 2345
Index 5: 6783
Index 6: 987
Index 7: 1234
Index 8: 8765
Index 9: 3456


Using iter and next functions:
1225
4986


Using map function to double the numbers:
[2450, 9972, 13578, 15780, 4690, 13566, 1974, 2468, 17530, 6912]


Using zip function to pair elements with their index:
[(0, 1225), (1, 4986), (2, 6789), (3, 7890), (4, 2345), (5, 6783), (6, 987), (7, 1234), (8, 8765), (9, 3456)]


Using NumPy module to perform operations on the list:
Adding 10 to each element:
[1235 4996 6799 7900 2355 6793  997 1244 8775 3466]

Multiplying each element by 2:
[ 2450  9972 13578 15780  4690 13566  197

**3)	For a List A, B, C, D, E write a python program to compute all the combinations and permutations**

In [4]:
# Function to generate combinations
def generate_combinations(current, index, lst):
    if index == len(lst):
        if current:
            print(tuple(current))
        return
    generate_combinations(current, index + 1, lst)
    generate_combinations(current + [lst[index]], index + 1, lst)
# Function to generate permutations
def generate_permutations(lst, start, end):
    if start == end:
        print(tuple(lst))
    else:
        for i in range(start, end):
            lst[start], lst[i] = lst[i], lst[start]  # Swap
            generate_permutations(lst, start + 1, end)
            lst[start], lst[i] = lst[i], lst[start]  # Swap back to backtrack
# List
my_list = ['A', 'B', 'C', 'D', 'E']
# All combinations
print("Combinations:")
generate_combinations([], 0, my_list)
# All permutations
print("\nPermutations:")
generate_permutations(my_list, 0, len(my_list))

Combinations:
('E',)
('D',)
('D', 'E')
('C',)
('C', 'E')
('C', 'D')
('C', 'D', 'E')
('B',)
('B', 'E')
('B', 'D')
('B', 'D', 'E')
('B', 'C')
('B', 'C', 'E')
('B', 'C', 'D')
('B', 'C', 'D', 'E')
('A',)
('A', 'E')
('A', 'D')
('A', 'D', 'E')
('A', 'C')
('A', 'C', 'E')
('A', 'C', 'D')
('A', 'C', 'D', 'E')
('A', 'B')
('A', 'B', 'E')
('A', 'B', 'D')
('A', 'B', 'D', 'E')
('A', 'B', 'C')
('A', 'B', 'C', 'E')
('A', 'B', 'C', 'D')
('A', 'B', 'C', 'D', 'E')

Permutations:
('A', 'B', 'C', 'D', 'E')
('A', 'B', 'C', 'E', 'D')
('A', 'B', 'D', 'C', 'E')
('A', 'B', 'D', 'E', 'C')
('A', 'B', 'E', 'D', 'C')
('A', 'B', 'E', 'C', 'D')
('A', 'C', 'B', 'D', 'E')
('A', 'C', 'B', 'E', 'D')
('A', 'C', 'D', 'B', 'E')
('A', 'C', 'D', 'E', 'B')
('A', 'C', 'E', 'D', 'B')
('A', 'C', 'E', 'B', 'D')
('A', 'D', 'C', 'B', 'E')
('A', 'D', 'C', 'E', 'B')
('A', 'D', 'B', 'C', 'E')
('A', 'D', 'B', 'E', 'C')
('A', 'D', 'E', 'B', 'C')
('A', 'D', 'E', 'C', 'B')
('A', 'E', 'C', 'D', 'B')
('A', 'E', 'C', 'B', 'D')
('A', 'E', 'D',

**4)	Using the same list use itertools compute permutations and combinations**

In [5]:
import itertools

# List
my_list = ['A', 'B', 'C', 'D', 'E']

# All combinations of all lengths
print("Combinations:")
for r in range(1, len(my_list) + 1):
    combinations = itertools.combinations(my_list, r)
    for combo in combinations:
        print(combo)

# All permutations of all lengths
print("\nPermutations:")
for r in range(1, len(my_list) + 1):
    permutations = itertools.permutations(my_list, r)
    for perm in permutations:
        print(perm)

Combinations:
('A',)
('B',)
('C',)
('D',)
('E',)
('A', 'B')
('A', 'C')
('A', 'D')
('A', 'E')
('B', 'C')
('B', 'D')
('B', 'E')
('C', 'D')
('C', 'E')
('D', 'E')
('A', 'B', 'C')
('A', 'B', 'D')
('A', 'B', 'E')
('A', 'C', 'D')
('A', 'C', 'E')
('A', 'D', 'E')
('B', 'C', 'D')
('B', 'C', 'E')
('B', 'D', 'E')
('C', 'D', 'E')
('A', 'B', 'C', 'D')
('A', 'B', 'C', 'E')
('A', 'B', 'D', 'E')
('A', 'C', 'D', 'E')
('B', 'C', 'D', 'E')
('A', 'B', 'C', 'D', 'E')

Permutations:
('A',)
('B',)
('C',)
('D',)
('E',)
('A', 'B')
('A', 'C')
('A', 'D')
('A', 'E')
('B', 'A')
('B', 'C')
('B', 'D')
('B', 'E')
('C', 'A')
('C', 'B')
('C', 'D')
('C', 'E')
('D', 'A')
('D', 'B')
('D', 'C')
('D', 'E')
('E', 'A')
('E', 'B')
('E', 'C')
('E', 'D')
('A', 'B', 'C')
('A', 'B', 'D')
('A', 'B', 'E')
('A', 'C', 'B')
('A', 'C', 'D')
('A', 'C', 'E')
('A', 'D', 'B')
('A', 'D', 'C')
('A', 'D', 'E')
('A', 'E', 'B')
('A', 'E', 'C')
('A', 'E', 'D')
('B', 'A', 'C')
('B', 'A', 'D')
('B', 'A', 'E')
('B', 'C', 'A')
('B', 'C', 'D')
('B', 'C